### ISSUE TITLE
Fix README references

### ISSUE THREAD

**Issue by michaelachrisco** [Quill-OS/quill#76]
I found a number of links that no longer go anywhere on the README. I believe this is because the project changed its name relatively recently. 

I believe all references to InkBox should be https://github.com/Quill-OS

and it should fix a couple of links in the official README. I also notice that the main site has been down for a bit: "This app is currently not responding. Please try refreshing the page in a few minutes." Maybe for now redirect to https://inkbox.ddns.net/ ? 
Ill make a quick PR to fix the references.

**Comment by Szybet** [comment]
which main website? https://inkbox.ddns.net/ is our main website for now

as for the links, nah, i will soon make a new website and fix the readme & other things

but thanks for caring

**Comment by Szybet** [comment]
oh yea, im working on that

**Comment by michaelachrisco** [comment]
coo no rush.
