### ISSUE TITLE
Kobo Aura

### ISSUE THREAD

**Issue by iddu0** [Quill-OS/quill#81]
Can I install quill-os to a Kobo Aura (**not HD**) without opening the device up? Maybe I could flash using balenaEtcher to the kobo via USB? If so, can I install quill Alongside the stock OS?

**Comment by Szybet** [comment]
No No No No

You would need to port it first

installing without opening is work in progress

**Comment by iddu0** [comment]
So I do have to open it? Is there a tutorial? And what do you mean by i have to port it first?
Thanks so much!

**Comment by Szybet** [comment]
It's not a supported device, porting means adapting the software to work with it

**Comment by iddu0** [comment]
Oh, thanks anyway! 
How can I port it?

**Comment by Szybet** [comment]
join our discord server and read other porting threads to understand the process

**Comment by iddu0** [comment]
Ok, Thanks for helping!
