### ISSUE TITLE
Add-on package?

### ISSUE THREAD

**Issue by joukepouke-pers** [Quill-OS/quill#86]
Is there going to be a package to install and run via nickelmenu/kfmon for the latest version of inkbox, ever?

**Comment by Szybet** [comment]
https://github.com/Quill-OS/QuillWrite
In the long future, some progress was made, maybe idk, we will see, dark times
but for now
![image](https://github.com/user-attachments/assets/f1127980-13f6-478c-9ae1-b8d65c35a341)

**Comment by tux-linux** [comment]
No, it has grown too much to be operated from an add-on package, it now needs its own operating system. There is an ongoing porting effort to port it to Libra 2 and Libra Colour devices currently.

**Comment by Szybet** [comment]
I meand to run and install inkbox, replacing the original os, well whatever

**Comment by joukepouke-pers** [comment]
Ok. And other way around? Kfmon on inkbox os?

**Comment by Szybet** [comment]
![image](https://github.com/user-attachments/assets/37b52bc4-8183-44fe-9fd1-9a6a142e5499)
